### ISSUE TITLE
メッシュ消失問題

### ISSUE THREAD

**Issue by Minemu398** [refiaa/MeshDecimater_Unity#15]
### MeshDecimater_Unity Version

v0.0.9.1

### Unity Version

Unity 2022.3.22f1

### Reproduction Steps

1.メッシュを選択してオプティマイズし、Mesh Optimizerのウインドウを閉じる

2.再度同じメッシュを選択してオプティマイズする

### Expected Behavior

メッシュが消える

### Actual Behavior

メッシュが消える

**Comment by refiaa** [comment]
+ Preview doesnt update after 1st `apply optimize`.
+ original mesh's GUID is depend on window update ? <- checking now
